### PR TITLE
Fixed link to "Pa11y Dashboard" in readme.md

### PR DESCRIPTION
**Pull request by jtechera**
Changed the format of the link from [name](link) to [name][link]

### CODE REVIEW

**Comment by joeyciechanowicz** [comment]
Thanks for contributing.

But doens't this create an incorrect link? It's meant to be `[name](link)` in markdown isn't it?

**Comment by jtechera** [comment]
Hi Joey,
I think it is `[name](link)` if "link" is the URL and [name][link] when you are using [reference-style](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) links.

**Comment by joeyciechanowicz** [comment]
Ah nifty @jtechera, TIL! Thanks for fixing that.

**Comment by jtechera** [comment]
Glad I could help!
Thanks!

**Pull request merged**
