### PR TITLE
beforeScript in webservice

### PR DESCRIPTION
**Pull request by una**
Hi! This PR adds the beforeScript option to the webservice, taking an input string and evaluating it within a function. Tests are passing, but I'm not entirely sure how to tell that it is being properly evaluated. I would love your thoughts and experience on it!

### CODE REVIEW

**Comment by rowanmanning** [comment]
Thanks, Una! Will talk through this as soon as I can :)

**Comment by una** [comment]
Any updates on this? I was getting errors in Travis for using `eval`, as recommended :/

**Comment by rowanmanning** [comment]
Hey Una, yeah this is still on my radar but haven't quite had time to pull it down and look, will get on it soon. Hope you had a nice Christmas!

**Comment by joeyciechanowicz** [comment]
Hi @una. Pa11y-webservice now supports [`actions`](https://github.com/pa11y/pa11y#actions) which provides the functionality of this PR.
If there is a specific action required, then `pa11y` itself would be the place to raise a PR.
Thanks for contributing

**Pull request closed without merging**
